#if !canImport(ObjectiveC)
import XCTest

extension NSString_RemoveEmojiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NSString_RemoveEmojiTests = [
        ("testContainsEmoji", testContainsEmoji),
        ("testRemovingEmoji", testRemovingEmoji),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NSString_RemoveEmojiTests.__allTests__NSString_RemoveEmojiTests),
    ]
}
#endif
